Restrict access in home content block
CodiTramuntana/decidim-suara-app pull request #44
Opened 2021-03-23 14:24 UTC by LauraJaimeC

#### :tophat: What? Why?

- [ ] Assemblies
- [ ] Consultations
- [ ] Participatory processes

#### :clipboard: Subtasks
- [ ] Add tests
- [ ] Add documentation regarding the feature 
- [ ] Add/modify seeds
- [ ] Another subtask

### :camera: Screenshots (optional)
![Description](URL)

2021-03-24 07:54 UTC, tramuntanal requested changes
Good job @LauraJaimeC !

I've left you a recommendation to be applied to all decorators so that if the decorated command changes, the decorators are not affected.

2021-03-24 07:54 UTC, tramuntanal commented on app/decorators/cells/decidim/assemblies/content_blocks/highlighted_assemblies_cell_decorator.rb
> +                                  Decidim::Assemblies::OrganizationPrioritizedAssemblies
Usually if we want the standard behavior we delegate to the decorated method. Check this example: https://github.com/gencat/participa-catalunya/blob/master/app/decorators/decidim/courses/controllers/admin/courses_controller_decorator.rb

2021-03-24 07:54 UTC, tramuntanal commented on spec/cells/decidim/assemblies/content_blocks/highlighted_assemblies_cell_spec.rb
> +        controller Decidim::PagesController
Shouldn't it be `homepage_controller`?

2021-03-24 07:54 UTC, tramuntanal commented on spec/cells/decidim/consultations/content_blocks/highlighted_consultations_cell_spec.rb
> +        controller Decidim::PagesController
Shouldn't it be `homepage_controller`?

2021-03-24 07:54 UTC, tramuntanal commented on spec/cells/decidim/participatory_processes/content_blocks/highlighted_processes_cell_spec.rb
> +        controller Decidim::PagesController
Shouldn't it be `homepage_controller`?

2021-03-24 09:06 UTC, LauraJaimeC commented
Changes applied!

2021-03-25 10:46 UTC, tramuntanal submitted a review, later dismissed
LGTM!

2021-04-06 13:14 UTC, merged