Fine Suara permissions control
CodiTramuntana/decidim-suara-app pull request #62
Opened 2021-12-14 14:21 UTC by tramuntanal

#### :tophat: What? Why?
A basic improvement of security to avoid direct access to restricted contents as defined by Suara permissions.

Contents were already filtered and hidden to the users but this PR avoids direct access by hacking the url.

2021-12-20 08:26 UTC, LauraJaimeC requested changes
Good job!! 💪🏼  Just a few details!

2021-12-20 08:26 UTC, LauraJaimeC commented on spec/controllers/components_controller_spec.rb
> +      end
Maybe you can test it too when space has one permission but not another, for example: 

```
let!(:space_with_one_permission) do
        create(
          :consultation,
          :published,
          organization: organization,
          suara_permissions: { ceco: "ceco", ceco_txt: "b" }
        )
      end
```

2021-12-20 08:26 UTC, LauraJaimeC commented on spec/controllers/comments_controller_spec.rb
> +      end
Maybe you can test it too when space has one permission but not another, for example: 

```
let!(:space_with_one_permission) do
        create(
          :consultation,
          :published,
          organization: organization,
          suara_permissions: { ceco: "ceco", ceco_txt: "b" }
        )
      end
```

2021-12-20 08:26 UTC, LauraJaimeC commented on app/decorators/controllers/decidim/assemblies/assemblies_controller_decorator.rb
> +    render status: :forbidden unless current_user.admin? || suara_permissions_match?(current_user, current_participatory_space)
It is a good idea to extract that condition in an method? What do you think?

2021-12-21 12:46 UTC, tramuntanal commented
Changes applied @LauraJaimeC

2021-12-21 15:01 UTC, LauraJaimeC approved these changes
LGTM!!

2022-01-11 13:21 UTC, merged