Update to Decidim 0.27
CodiTramuntana/decidim-suara-app pull request #99
Opened 2023-06-02 09:03 UTC by NicoleSo13

This PR upgrades the Suara App to Decidim v0.27.3.

TODO:
- Fix action_delegator voted_with_direct_verification
- Fix Rubocop
- Fix Specs

Release: https://github.com/decidim/decidim/releases :
- 0.27.3 : https://github.com/decidim/decidim/releases/tag/v0.27.3
- 0.27.2 : https://github.com/decidim/decidim/releases/tag/v0.27.2
- 0.27.1 : https://github.com/decidim/decidim/releases/tag/v0.27.1
- 0.27.0: https://github.com/decidim/decidim/releases/tag/v0.27.0 

Note that many Decidim configuration has moved from the `config/initializers/decidim.rb` to ENV variables. See https://github.com/decidim/decidim/pull/8725 for a full list of ENV vars.

To execute after deploy:
https://github.com/decidim/decidim/blob/release/0.27-stable/CHANGELOG.md#3-one-time-actions

2023-06-30 12:51 UTC, tramuntanal requested changes
Geat work!
Please check my comments to refine the details :smile:

2023-06-30 12:51 UTC, tramuntanal commented on config/initializers/decidim/meetings/component_filterable_override.rb
why an initializer? can't it be in app/decorators for example?
or in `lib/config/initializers/decidim/meetings/component_filterable.rb`

2023-06-30 12:51 UTC, tramuntanal commented on app/views/decidim/meetings/meetings/_filters.html.erb
> +  <%# Suara customization %>
```suggestion
  <%# START Suara customization %>
```

2023-06-30 12:51 UTC, tramuntanal commented on app/views/decidim/meetings/meetings/_filters.html.erb
> +  <%# Suara customization %>
```suggestion
  <%# END Suara customization %>
```

2023-06-30 12:51 UTC, tramuntanal commented on app/views/decidim/meetings/meetings/_meetings.html.erb
> +<%# Suara customization %>
```suggestion
<%# START Suara customization %>
```

2023-06-30 12:51 UTC, tramuntanal commented on app/views/decidim/meetings/meetings/_meetings.html.erb
> +<%# Suara customization %>
```suggestion
<%# END Suara customization %>
```

2023-06-30 12:51 UTC, tramuntanal commented on .gitignore
> +
must add the other variants?
```suggestion
/public/sw.js
/public/sw.js.br
/public/sw.js.gz
/public/sw.js.map
/public/sw.js.map.br
/public/sw.js.map.gz
```

2023-06-30 12:51 UTC, tramuntanal commented on app/packs/entrypoints/application.js
empty?

2023-06-30 12:51 UTC, tramuntanal commented on app/packs/src/decidim/editor.js
is this file being compiled or used anywhere?

2023-07-04 08:26 UTC, laurajaime commented on config/initializers/decidim/meetings/component_filterable_override.rb
It's because a concern and it so complicated to override this hash...this is the best way I have found after much testing. I have tried the two ways you mention and neither works.

Do you know any better?

2023-07-04 08:28 UTC, laurajaime commented on app/packs/src/decidim/editor.js
yes...this file is an override of quillEditor

2023-07-04 08:29 UTC, laurajaime commented on app/packs/entrypoints/application.js
Yes, its ok

2023-08-22 11:32 UTC, tramuntanal submitted a review, later dismissed
LGTM

2023-08-22 11:36 UTC, tramuntanal commented
I've run the validate migrations locally and it succeeds. Can not re-run on GitHub Actions.

2023-10-10 10:34 UTC, laurajaime submitted a review, later dismissed

2023-10-25 09:50 UTC, laurajaime approved these changes

2023-10-25 10:14 UTC, merged